### ISSUE TITLE
获取音乐信息失败

### ISSUE THREAD

**Issue by jimmysoar** [lchloride/NeteaseMusicCacheDecode#6]
![image](https://user-images.githubusercontent.com/5345608/39353099-435f47a8-4a39-11e8-8d4c-567a8c2c82c0.png)

网络没有问题

**Comment by jimmysoar** [comment]
不是音乐的问题，换了好多个 .uc 文件，问题依旧。批量处理时候，缓存大约100-200个文件，全部获取音乐信息失败。

**Comment by lchloride** [comment]
出现这个问题的原因是程序无法解析从网络中获取的音乐数据。
根据您发给我的截图，处理失败的这首歌应该是陈芳语的《爱你》，歌曲编号是22852057.
由于地区限制，我没办法直接缓存这首歌曲。不过我模拟了一下缓存转换的过程，并且得到了正确的结果。
![c1](https://user-images.githubusercontent.com/22909207/39830340-2753d024-538f-11e8-841a-c0cd001ae155.PNG)
为了确定是不是系统兼容性的问题，我也尝试了Win7(本人用的是Win10)，也得到了正确的结果。
<img width="450" alt="c2" src="https://user-images.githubusercontent.com/22909207/39832159-786c2592-5394-11e8-947c-d731b426f949.PNG">
如果您多次尝试依然不能成功，请发几个缓存文件我来试一下。
最后，感谢您的支持

**Comment by jimmysoar** [comment]
已经没有问题了，估计本地获取网易服务器数据失败的问题。
